// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PrintNest.Infrastructure.Persistence;

#nullable disable

namespace PrintNest.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260306204750_AddRetryableFailedOtpRegeneration")]
    partial class AddRetryableFailedOtpRegeneration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PrintNest.Domain.Entities.AuditEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<string>("MetaJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("meta_json");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("JobId")
                        .HasDatabaseName("ix_audit_events_job_id");

                    b.ToTable("audit_events", (string)null);
                });

            modelBuilder.Entity("PrintNest.Domain.Entities.Device", b =>
                {
                    b.Property<string>("DeviceId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("device_id");

                    b.Property<string>("CapabilitiesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("capabilities_json");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastHeartbeatUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_heartbeat_utc");

                    b.Property<bool?>("PrinterCartridgeMissing")
                        .HasColumnType("boolean")
                        .HasColumnName("printer_cartridge_missing");

                    b.Property<DateTime?>("PrinterCartridgeMissingSinceUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("printer_cartridge_missing_since_utc");

                    b.Property<int>("PrinterConnectionFlapTransitions")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("printer_connection_flap_transitions");

                    b.Property<DateTime?>("PrinterConnectionFlapWindowStartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("printer_connection_flap_window_started_at_utc");

                    b.Property<string>("PrinterConnectionState")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("printer_connection_state");

                    b.Property<bool?>("PrinterDoorOpen")
                        .HasColumnType("boolean")
                        .HasColumnName("printer_door_open");

                    b.Property<DateTime?>("PrinterDoorOpenSinceUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("printer_door_open_since_utc");

                    b.Property<DateTime?>("PrinterErrorSinceUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("printer_error_since_utc");

                    b.Property<DateTime?>("PrinterInkLowSinceUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("printer_ink_low_since_utc");

                    b.Property<string>("PrinterInkState")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("printer_ink_state");

                    b.Property<DateTime?>("PrinterInkStateChangedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("printer_ink_state_changed_at_utc");

                    b.Property<double?>("PrinterLowToEmptyAvgMinutes")
                        .HasColumnType("double precision")
                        .HasColumnName("printer_low_to_empty_avg_minutes");

                    b.Property<int>("PrinterLowToEmptySamples")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("printer_low_to_empty_samples");

                    b.Property<string>("PrinterModel")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("printer_model");

                    b.Property<DateTime?>("PrinterOfflineSinceUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("printer_offline_since_utc");

                    b.Property<string>("PrinterOperationalState")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("printer_operational_state");

                    b.Property<bool?>("PrinterPaperOut")
                        .HasColumnType("boolean")
                        .HasColumnName("printer_paper_out");

                    b.Property<DateTime?>("PrinterPaperOutSinceUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("printer_paper_out_since_utc");

                    b.Property<string>("PrinterRawStatusJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("printer_raw_status_json");

                    b.Property<DateTime?>("PrinterStatusUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("printer_status_updated_at_utc");

                    b.Property<string>("SharedSecret")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("shared_secret");

                    b.Property<string>("StoreId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("store_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("DeviceId");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_devices_is_active");

                    b.HasIndex("PrinterStatusUpdatedAtUtc")
                        .HasDatabaseName("ix_devices_printer_status_updated");

                    b.HasIndex("StoreId")
                        .HasDatabaseName("ix_devices_store_id");

                    b.ToTable("devices", (string)null);
                });

            modelBuilder.Entity("PrintNest.Domain.Entities.PrintJob", b =>
                {
                    b.Property<Guid>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("job_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AssignedDeviceId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("assigned_device_id");

                    b.Property<string>("AssignedStoreId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("assigned_store_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("INR")
                        .HasColumnName("currency");

                    b.Property<bool>("DeletePending")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("delete_pending");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("ObjectKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("object_key");

                    b.Property<string>("OptionsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("options_json");

                    b.Property<int>("OtpAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("otp_attempts");

                    b.Property<DateTime?>("OtpExpiryUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("otp_expiry_utc");

                    b.Property<string>("OtpHash")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("otp_hash");

                    b.Property<DateTime?>("OtpLastAttemptUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("otp_last_attempt_utc");

                    b.Property<DateTime?>("OtpLockedUntilUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("otp_locked_until_utc");

                    b.Property<int>("PriceCents")
                        .HasColumnType("integer")
                        .HasColumnName("price_cents");

                    b.Property<DateTime?>("PrintedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("printed_at_utc");

                    b.Property<DateTime?>("ReleaseLockUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("release_lock_utc");

                    b.Property<bool>("RetryAllowed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("retry_allowed");

                    b.Property<string>("Sha256")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sha256");

                    b.Property<string>("Status")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("JobId");

                    b.HasIndex("AssignedDeviceId")
                        .HasDatabaseName("ix_print_jobs_assigned_device");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("ix_print_jobs_created_at");

                    b.HasIndex("DeletePending")
                        .HasDatabaseName("ix_print_jobs_delete_pending");

                    b.HasIndex("OtpExpiryUtc")
                        .HasDatabaseName("ix_print_jobs_otp_expiry");

                    b.HasIndex("RetryAllowed")
                        .HasDatabaseName("ix_print_jobs_retry_allowed");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_print_jobs_status");

                    b.ToTable("print_jobs", (string)null);
                });

            modelBuilder.Entity("PrintNest.Domain.Entities.StaffUser", b =>
                {
                    b.Property<Guid>("StaffUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("staff_user_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at_utc");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role");

                    b.Property<string>("StoreId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("store_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("username");

                    b.HasKey("StaffUserId");

                    b.HasIndex("Role")
                        .HasDatabaseName("ix_staff_users_role");

                    b.HasIndex("StoreId")
                        .HasDatabaseName("ix_staff_users_store_id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ux_staff_users_username");

                    b.ToTable("staff_users", (string)null);
                });

            modelBuilder.Entity("PrintNest.Domain.Entities.Store", b =>
                {
                    b.Property<string>("StoreId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("store_id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("StoreId");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_stores_is_active");

                    b.ToTable("stores", (string)null);
                });

            modelBuilder.Entity("PrintNest.Domain.Entities.UsedFileToken", b =>
                {
                    b.Property<string>("Jti")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("jti");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("device_id");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<DateTime>("UsedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at_utc");

                    b.HasKey("Jti");

                    b.HasIndex("UsedAtUtc")
                        .HasDatabaseName("ix_used_file_tokens_used_at");

                    b.ToTable("used_file_tokens", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
