namespace PrintNest.Domain.Entities;

/// <summary>
/// A Raspberry Pi (or any Linux device) registered in the network.
///
/// Devices authenticate using HMAC-SHA256 with their SharedSecret.
/// Credentials are generated by the provisioning script (tools/provision-device.sh)
/// and registered via POST /api/v1/admin/devices.
///
/// To deactivate a device: set IsActive = false via PATCH /api/v1/admin/devices/{id}.
/// </summary>
public sealed class Device
{
    /// <summary>
    /// Unique identifier. Format: dev_{storeId}_{random8}.
    /// Generated by the provisioning script.
    /// </summary>
    public string DeviceId { get; init; } = string.Empty;

    /// <summary>Store this device belongs to. Can be null if not yet assigned to a store.</summary>
    public string? StoreId { get; set; }

    /// <summary>
    /// HMAC shared secret. Stored in plaintext — required for HMAC-SHA256 verification.
    /// 32 bytes, base64url-encoded. Generated by the provisioning script.
    /// This is the only field that must never be logged.
    /// </summary>
    public string SharedSecret { get; set; } = string.Empty;

    /// <summary>Last time this device sent a heartbeat. Used to determine if device is online.</summary>
    public DateTime? LastHeartbeatUtc { get; set; }

    /// <summary>
    /// Device capabilities as JSON. Schema: { printers: string[], cupsPrinters: string[] }
    /// Updated on each heartbeat. Stored raw for forward compatibility.
    /// </summary>
    public string? CapabilitiesJson { get; set; }

    // â”€â”€ Printer health telemetry (normalized, model-agnostic backend shape) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

    /// <summary>Device-reported printer model (for example "HP DeskJet 2338").</summary>
    public string? PrinterModel { get; set; }

    /// <summary>Connection state: ONLINE | OFFLINE | UNKNOWN.</summary>
    public string? PrinterConnectionState { get; set; }

    /// <summary>Operational state: IDLE | PRINTING | ERROR | UNKNOWN.</summary>
    public string? PrinterOperationalState { get; set; }

    /// <summary>True if paper is out.</summary>
    public bool? PrinterPaperOut { get; set; }

    /// <summary>True if cover/door is open.</summary>
    public bool? PrinterDoorOpen { get; set; }

    /// <summary>True if cartridge is missing.</summary>
    public bool? PrinterCartridgeMissing { get; set; }

    /// <summary>Ink warning state: OK | LOW | VERY_LOW | EMPTY | UNKNOWN.</summary>
    public string? PrinterInkState { get; set; }

    /// <summary>Raw backend-agnostic status payload from agent for debugging.</summary>
    public string? PrinterRawStatusJson { get; set; }

    /// <summary>When printer telemetry was last updated by heartbeat.</summary>
    public DateTime? PrinterStatusUpdatedAtUtc { get; set; }

    /// <summary>
    /// Soft delete flag. When false, the device is treated as unknown by the auth middleware.
    /// Use this instead of deleting the row to preserve audit history.
    /// </summary>
    public bool IsActive { get; set; } = true;

    public DateTime CreatedAtUtc { get; init; } = DateTime.UtcNow;
    public DateTime UpdatedAtUtc { get; set; } = DateTime.UtcNow;
}
