namespace PrintNest.Domain.Entities;

/// <summary>
/// A Raspberry Pi (or any Linux device) registered in the network.
///
/// Devices authenticate using HMAC-SHA256 with their SharedSecret.
/// Credentials are generated by the provisioning script (tools/provision-device.sh)
/// and registered via POST /api/v1/admin/devices.
///
/// To deactivate a device: set IsActive = false via PATCH /api/v1/admin/devices/{id}.
/// </summary>
public sealed class Device
{
    /// <summary>
    /// Unique identifier. Format: dev_{storeId}_{random8}.
    /// Generated by the provisioning script.
    /// </summary>
    public string DeviceId { get; init; } = string.Empty;

    /// <summary>Store this device belongs to. Can be null if not yet assigned to a store.</summary>
    public string? StoreId { get; set; }

    /// <summary>
    /// HMAC shared secret. Stored in plaintext — required for HMAC-SHA256 verification.
    /// 32 bytes, base64url-encoded. Generated by the provisioning script.
    /// This is the only field that must never be logged.
    /// </summary>
    public string SharedSecret { get; set; } = string.Empty;

    /// <summary>Last time this device sent a heartbeat. Used to determine if device is online.</summary>
    public DateTime? LastHeartbeatUtc { get; set; }

    /// <summary>
    /// Device capabilities as JSON. Schema: { printers: string[], cupsPrinters: string[] }
    /// Updated on each heartbeat. Stored raw for forward compatibility.
    /// </summary>
    public string? CapabilitiesJson { get; set; }

    /// <summary>
    /// Soft delete flag. When false, the device is treated as unknown by the auth middleware.
    /// Use this instead of deleting the row to preserve audit history.
    /// </summary>
    public bool IsActive { get; set; } = true;

    public DateTime CreatedAtUtc { get; init; } = DateTime.UtcNow;
    public DateTime UpdatedAtUtc { get; set; } = DateTime.UtcNow;
}
