using PrintNest.Domain.Enums;

namespace PrintNest.Domain.Entities;

/// <summary>
/// Core aggregate. Represents a single print job from upload to deletion.
///
/// State transitions are ONLY performed via JobStateMachine.Transition().
/// Never set Status directly from outside the domain layer.
///
/// All timestamps are UTC. Nullable fields are null until that lifecycle stage is reached.
/// </summary>
public sealed class PrintJob
{
    /// <summary>Primary key. Generated by the backend on job creation.</summary>
    public Guid JobId { get; init; } = Guid.NewGuid();

    /// <summary>Current state. Use JobStateMachine.Transition() to change this.</summary>
    public JobStatus Status { get; set; } = JobStatus.Draft;

    /// <summary>MinIO object key (path within the bucket). Set after upload finalized.</summary>
    public string? ObjectKey { get; set; }

    /// <summary>SHA-256 hex hash of the uploaded file. Provided by client on finalize.</summary>
    public string? Sha256 { get; set; }

    /// <summary>
    /// Print options as JSON. Schema: { copies: int, color: "BW" | "COLOR" }
    /// Stored as raw JSON so new options can be added without a migration.
    /// </summary>
    public string? OptionsJson { get; set; }

    /// <summary>Price in smallest currency unit (paise for INR). Set during quote.</summary>
    public int PriceCents { get; set; }

    /// <summary>ISO 4217 currency code. Default: INR.</summary>
    public string Currency { get; set; } = "INR";

    // ── OTP fields ────────────────────────────────────────────────

    /// <summary>Argon2id hash of the OTP. Null when no active OTP exists.</summary>
    public string? OtpHash { get; set; }

    /// <summary>When the current OTP expires. 6 hours from generation time.</summary>
    public DateTime? OtpExpiryUtc { get; set; }

    /// <summary>
    /// Number of failed OTP attempts against the current OTP.
    /// Resets to 0 each time a new OTP is generated.
    /// When this reaches 6, the job is locked — OtpLockedUntilUtc is set.
    /// </summary>
    public int OtpAttempts { get; set; } = 0;

    /// <summary>Timestamp of the last OTP attempt (any device). Used for per-minute rate limiting.</summary>
    public DateTime? OtpLastAttemptUtc { get; set; }

    /// <summary>
    /// When set, OTP attempts are rejected with OTP_LOCKED until this time passes.
    /// Set after 6 consecutive failed attempts.
    /// </summary>
    public DateTime? OtpLockedUntilUtc { get; set; }

    // ── Assignment fields (set at Release time) ───────────────────

    /// <summary>Device that released this job. Null until Released state.</summary>
    public string? AssignedDeviceId { get; set; }

    /// <summary>Store where the job was released. Null until Released state.</summary>
    public string? AssignedStoreId { get; set; }

    /// <summary>Timestamp when the release lock was acquired. Used for audit and stuck-job detection.</summary>
    public DateTime? ReleaseLockUtc { get; set; }

    // ── Failure details (last failure only) ──────────────────────

    /// <summary>
    /// Short code identifying why the job last failed.
    /// Set by the device (e.g. "PAPER_OUT", "PAPER_JAM", "CUPS_ERROR") or by the
    /// watchdog worker (e.g. "WATCHDOG_TIMEOUT").
    /// Cleared when the job is released for retry or completes successfully.
    /// </summary>
    public string? LastFailureCode { get; set; }

    /// <summary>
    /// Human-readable failure description, forwarded from the device or worker.
    /// Cleared alongside LastFailureCode.
    /// </summary>
    public string? LastFailureMessage { get; set; }

    // ── Completion / deletion fields ──────────────────────────────

    /// <summary>Timestamp when the device confirmed print completed.</summary>
    public DateTime? PrintedAtUtc { get; set; }

    /// <summary>
    /// True when an unfinished failed/interrupted job may reuse the same OTP and retry from scratch.
    /// Cleared once the job becomes non-retryable or reaches a terminal state.
    /// </summary>
    public bool RetryAllowed { get; set; } = false;

    /// <summary>Timestamp when the file was deleted from MinIO and job moved to Deleted.</summary>
    public DateTime? DeletedAtUtc { get; set; }

    /// <summary>
    /// True when MinIO deletion failed and the cleanup worker should retry.
    /// The cleanup worker sets this to false on successful retry.
    /// </summary>
    public bool DeletePending { get; set; } = false;

    // ── Standard timestamps ───────────────────────────────────────

    public DateTime CreatedAtUtc { get; init; } = DateTime.UtcNow;
    public DateTime UpdatedAtUtc { get; set; } = DateTime.UtcNow;
}
